[package]
name = "record-account"
version = "0.1.0"
edition = "2024"

[dependencies]
binance = "0.21.0"
chrono = "0.4.39"
datatypes = { path = "../datatypes" }
serde = "1.0.217"
serde_json = "1.0.135"
tungstenite = { version = "0.26.1", features = ["native-tls"] }
url = "2.5.4"
