[package]
name = "replay"
version = "0.1.0"
edition = "2021"

[dependencies]
binance = "0.21.0"
serde = "1.0.216"
serde_json = "1.0.134"
datatypes = { path = "../datatypes" }
indicatif = "0.17.9"
human-repr = "1.1.0"