[package]
name = "datatypes"
version = "0.1.0"
edition = "2021"

[dependencies]
binance = "0.21.0"
charming = {version = "0.4.0", features = ["ssr"]}
opener = "0.7.2"
serde = "1.0.216"
serde_json = "1.0.135"
